### ISSUE TITLE
Unable to view newly uploaded samples.

### ISSUE THREAD

**Issue by vxunderground** [blackmassgroup/vx_underground#10]
Uploaded file hash: c1e630b6c647ed0f0ffa4912d01d863c495da6332b5972cdfb2e0116b6cb11a2

File uploads successfully, file is able to be found when you search for the file. However, you can not view the file
![1](https://github.com/blackmassgroup/vx_underground/assets/57078196/d33c8e10-a38e-49ba-a839-340d9298af51)
![2](https://github.com/blackmassgroup/vx_underground/assets/57078196/8478b6c2-3f3c-49ce-8459-2742fc792bee)

**Comment by guessthepw** [comment]
resolved
