### ISSUE TITLE
File Sample Upload/Search Error

### ISSUE THREAD

**Issue by BradleyVX** [blackmassgroup/vx_underground#4]
After uploading a sample to the database, the file successfully uploads to triage, but does not appear in the vxu.fly.dev database. When searching for the file's SHA256 in the database, a "we can't find the internet" message appears. 
![upload12](https://user-images.githubusercontent.com/132176982/236642686-84c3afbd-a253-4054-95f5-c845b7f45d14.png)

**Comment by guessthepw** [comment]
Pushed a fix, test again
