### ISSUE TITLE
Account Creation Error

### ISSUE THREAD

**Issue by BradleyVX** [blackmassgroup/vx_underground#5]
During account creation, the following error appears:
![accerror](https://github.com/blackmassgroup/vx_underground/assets/132176982/21d9bc72-d2c7-4ca6-ac74-4890817effb0)

**Comment by guessthepw** [comment]
This is fixed, manually imported user records from initial twitter post launch. Ran the sql command `ALTER SEQUENCE users_id_seq RESTART WITH 586`
