### ISSUE TITLE
Light Mode Glitch

### ISSUE THREAD

**Issue by BradleyVX** [blackmassgroup/vx_underground#6]
When switching between pages, light mode becomes disabled, aka switches to dark mode.

**Comment by yassirlaaouissi** [comment]
@BradleyVX it seems like the state of the dark mode toggle is not persistently stored in the user's session. Causing some inconsistent behavior (switch being on dark mode while screen is light mode). I attached a video of the behavior:

https://github.com/blackmassgroup/vx_underground/assets/59022605/6c1ab57e-cd2b-4fde-9279-c39d27b726f2

**Comment by guessthepw** [comment]
No more lightmode
