### ISSUE TITLE
Light mode sample counter borked

### ISSUE THREAD

**Issue by yassirlaaouissi** [blackmassgroup/vx_underground#7]
Hey,

The sample counter is invincible when switching to light mode:
![image](https://github.com/blackmassgroup/vx_underground/assets/59022605/a7f35ab8-aa49-4839-8e16-d57a827a9b0a)
Light mode:
![image](https://github.com/blackmassgroup/vx_underground/assets/59022605/9fb79824-109f-4e93-bf7f-f17d671a3119)

**Comment by guessthepw** [comment]
no more lightmore
